# Generated by Django 3.0.7 on 2020-07-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(editable=False)),
                ('payment_method', models.CharField(choices=[('M', 'Mpesa'), ('C', 'Card')], max_length=1)),
                ('paid', models.BooleanField(default=False, editable=False)),
                ('waiting', models.BooleanField(default=False, editable=False)),
                ('cancelled', models.BooleanField(default=False, editable=False)),
                ('failed', models.BooleanField(default=False, editable=False)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('last_edited_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to=settings.AUTH_USER_MODEL)),
                ('order',
                 models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('status', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider_channel', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('paid', models.BooleanField(default=False, editable=False)),
                ('waiting', models.BooleanField(default=False, editable=False)),
                ('failed', models.BooleanField(default=False, editable=False)),
                ('error_message', models.TextField(blank=True, editable=False, null=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('payment',
                 models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, editable=False)),
                ('provider_fee', models.FloatField(blank=True, editable=False, null=True)),
                ('africastalking_transaction_id',
                 models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('category', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider_ref_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider_channel', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('client_account', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('source', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('destination_type', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('value', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('transaction_fee', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('description', models.TextField(blank=True, editable=False, null=True)),
                ('provider_metadata', models.TextField(blank=True, editable=False, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                                     to='payments.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(editable=False, max_length=255)),
                ('transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                                     to='payments.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('waiting', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('last_edited_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to=settings.AUTH_USER_MODEL)),
                ('order',
                 models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('amount', models.FloatField()),
                ('last_edited_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
