# Generated by Django 3.0.7 on 2020-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
    ]
