# Generated by Django 3.0.7 on 2020-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200610_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
    ]
