# Generated by Django 3.0.7 on 2020-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
