# Generated by Django 3.0.7 on 2020-06-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_transaction_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
