# Generated by Django 3.0.7 on 2020-06-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200611_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cancelled',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='waiting',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='error_message',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='failed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_channel',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='waiting',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
