# Generated by Django 3.0.7 on 2020-06-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200611_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction')),
            ],
        ),
    ]
