# Generated by Django 3.0.7 on 2020-06-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_transactionphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionphone',
            name='phone_number',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionphone',
            name='transaction',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction'),
        ),
    ]
