# Generated by Django 3.0.7 on 2020-06-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200611_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, editable=False)),
                ('provider_fee', models.FloatField(blank=True, editable=False, null=True)),
                ('africastalking_transaction_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('category', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider_ref_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider_channel', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('client_account', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('source', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('destination_type', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('value', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('transaction_fee', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('description', models.TextField(blank=True, editable=False, null=True)),
                ('provider_metadata', models.TextField(blank=True, editable=False, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction')),
            ],
        ),
    ]
