# Generated by Django 3.0.7 on 2020-06-08 07:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='Kenya', max_length=2),
            preserve_default=False,
        ),
    ]
