# Generated by Django 3.0.7 on 2020-06-11 04:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='74564756475', max_length=13, validators=[accounts.models.validate_kenyan_phone]),
            preserve_default=False,
        ),
    ]
