# Generated by Django 3.0.7 on 2020-08-02 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_auto_20200730_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_variations',
        ),
    ]
