# Generated by Django 3.0.7 on 2020-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_auto_20200802_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='G', unique=True),
            preserve_default=False,
        ),
    ]
